List threeBearsScale = [
  {"image": "assets/images/scale/emptyScale.png", "time": 3000, "scale": "준비"},
  {"image": "assets/images/scale/emptyScale.png", "time": 2000, "scale": "시작!"},
  // 곰 세마리가
  {"image": "assets/images/scale/0.png", "time": 500, "scale": "도"},
  {"image": "assets/images/scale/emptyScale.png", "time": 500, "scale": ""},
  {"image": "assets/images/scale/0.png", "time": 500, "scale": "도"},
  {"image": "assets/images/scale/emptyScale.png", "time": 200, "scale": ""},
  {"image": "assets/images/scale/0.png", "time": 500, "scale": "도"},
  {"image": "assets/images/scale/emptyScale.png", "time": 200, "scale": ""},
  {"image": "assets/images/scale/0.png", "time": 500, "scale": "도"},
  {"image": "assets/images/scale/emptyScale.png", "time": 500, "scale": ""},
  {"image": "assets/images/scale/0.png", "time": 500, "scale": "도"},
  {"image": "assets/images/scale/emptyScale.png", "time": 500, "scale": ""},
  // 한 집에 있어
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "미"},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/emptyScale.png", "time": 100, "scale": ""},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "미"},
  {"image": "assets/images/scale/0.png", "time": 500, "scale": "도"},
  // 아빠곰 엄마곰
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/emptyScale.png", "time": 100, "scale": ""},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "미"},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/emptyScale.png", "time": 100, "scale": ""},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "미"},
  // 애기곰
  {"image": "assets/images/scale/0.png", "time": 500, "scale": "도"},
  {"image": "assets/images/scale/emptyScale.png", "time": 100, "scale": ""},
  {"image": "assets/images/scale/0.png", "time": 500, "scale": "도"},
  {"image": "assets/images/scale/emptyScale.png", "time": 100, "scale": ""},
  {"image": "assets/images/scale/0.png", "time": 2000, "scale": "도"},
  // 아빠곰은
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/emptyScale.png", "time": 100, "scale": ""},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "미"},
  {"image": "assets/images/scale/0.png", "time": 500, "scale": "도"},
  // 뚱뚱해
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/emptyScale.png", "time": 100, "scale": ""},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/emptyScale.png", "time": 100, "scale": ""},
  {"image": "assets/images/scale/4.png", "time": 2000, "scale": "솔"},
  {"image": "assets/images/scale/emptyScale.png", "time": 100, "scale": ""},
  // 엄마곰은
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/emptyScale.png", "time": 100, "scale": ""},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "미"},
  {"image": "assets/images/scale/0.png", "time": 500, "scale": "도"},
  // 날씬해
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/emptyScale.png", "time": 100, "scale": ""},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/emptyScale.png", "time": 100, "scale": ""},
  {"image": "assets/images/scale/4.png", "time": 2000, "scale": "솔"},
  {"image": "assets/images/scale/emptyScale.png", "time": 100, "scale": ""},
  // 애기곰은
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/emptyScale.png", "time": 100, "scale": ""},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "미"},
  {"image": "assets/images/scale/0.png", "time": 500, "scale": "도"},
  // 너무귀여워
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/emptyScale.png", "time": 100, "scale": ""},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/emptyScale.png", "time": 100, "scale": ""},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/5.png", "time": 500, "scale": "라"},
  {"image": "assets/images/scale/4.png", "time": 2000, "scale": "솔"},
  // 으쓱으쓱
  {"image": "assets/images/scale/7.png", "time": 500, "scale": "도"},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/7.png", "time": 500, "scale": "도"},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  // 잘한다
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "미"},
  {"image": "assets/images/scale/1.png", "time": 500, "scale": "레"},
  {"image": "assets/images/scale/0.png", "time": 2000, "scale": "도"},
];

List littleStarScale = [
  {"image": "assets/images/scale/emptyScale.png", "time": 3000, "scale": "준비"},
  {"image": "assets/images/scale/emptyScale.png", "time": 2000, "scale": "시작!"},
  // 반짝 반짝 작은별
  {"image": "assets/images/scale/0.png", "time": 500, "scale": "도"},
  {"image": "assets/images/scale/0.png", "time": 500, "scale": "도"},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/5.png", "time": 500, "scale": "라"},
  {"image": "assets/images/scale/5.png", "time": 500, "scale": "라"},
  {"image": "assets/images/scale/4.png", "time": 2000, "scale": "솔"},
  // 아름 답게 비치네
  {"image": "assets/images/scale/3.png", "time": 500, "scale": "파"},
  {"image": "assets/images/scale/3.png", "time": 500, "scale": "파"},
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "미"},
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "미"},
  {"image": "assets/images/scale/1.png", "time": 500, "scale": "도"},
  {"image": "assets/images/scale/1.png", "time": 500, "scale": "도"},
  {"image": "assets/images/scale/0.png", "time": 2000, "scale": "도"},
  // 동쪽 하늘 에서도
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/3.png", "time": 500, "scale": "파"},
  {"image": "assets/images/scale/3.png", "time": 500, "scale": "파"},
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "미"},
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "미"},
  {"image": "assets/images/scale/1.png", "time": 500, "scale": "레"},
  // 서쪽 하늘 에서도
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/3.png", "time": 500, "scale": "파"},
  {"image": "assets/images/scale/3.png", "time": 500, "scale": "파"},
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "미"},
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "미"},
  {"image": "assets/images/scale/1.png", "time": 500, "scale": "레"},
  // 반짝 반짝 작은별
  {"image": "assets/images/scale/0.png", "time": 500, "scale": "도"},
  {"image": "assets/images/scale/0.png", "time": 500, "scale": "도"},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/5.png", "time": 500, "scale": "라"},
  {"image": "assets/images/scale/5.png", "time": 500, "scale": "라"},
  {"image": "assets/images/scale/4.png", "time": 2000, "scale": "솔"},
  // 아름 답게 비치네
  {"image": "assets/images/scale/3.png", "time": 500, "scale": "파"},
  {"image": "assets/images/scale/3.png", "time": 500, "scale": "파"},
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "미"},
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "미"},
  {"image": "assets/images/scale/1.png", "time": 500, "scale": "도"},
  {"image": "assets/images/scale/1.png", "time": 500, "scale": "도"},
  {"image": "assets/images/scale/0.png", "time": 2000, "scale": "도"},
];

List schoolBellScale = [
  {"image": "assets/images/scale/emptyScale.png", "time": 3000, "scale": "준비"},
  {"image": "assets/images/scale/emptyScale.png", "time": 2000, "scale": "시작!"},
  // 학교 종이 땡땡땡
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/5.png", "time": 500, "scale": "라"},
  {"image": "assets/images/scale/5.png", "time": 500, "scale": "라"},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "미"},
  // 어서모이자
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "도"},
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "도"},
  {"image": "assets/images/scale/1.png", "time": 500, "scale": "레"},
  // 선생님이 우리를
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/5.png", "time": 500, "scale": "라"},
  {"image": "assets/images/scale/5.png", "time": 500, "scale": "라"},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "미"},
  // 기다리신다
  {"image": "assets/images/scale/4.png", "time": 500, "scale": "솔"},
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "도"},
  {"image": "assets/images/scale/1.png", "time": 500, "scale": "레"},
  {"image": "assets/images/scale/2.png", "time": 500, "scale": "도"},
  {"image": "assets/images/scale/0.png", "time": 2000, "scale": "도"},
];
